# docker-compose.yml
services:
    db:
        image: postgres:latest
        env_file: .env
        ports:
            - 5432:5432
        volumes:
           - pgdata:/var/lib/postgresql/data

    broker:
        image: "rabbitmq:3.8.18-management"
        container_name: broker
        ports:
        - "5672:5672"
        - "15672:15672"
        environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

    lfg-api:
        build:
            context:  ./services/lfg_bank
            target: DevService 
        container_name:  lfg-api
        env_file:  ./services/lfg_bank/.env
        command: /code/entrypoint.sh
        volumes:
            - ./services/lfg_bank:/code
        stdin_open: true
        tty: true
        ports:
            - 8000:8000
        depends_on:
            - db
            - broker
    
    lfg-celery:
        build:
            context:  ./services/lfg_bank
        container_name:  lfg-celery
        env_file:  ./services/lfg_bank/.env
        command: celery -A lfg_bank worker
        volumes:
            - ./services/lfg_bank:/code
        stdin_open: true
        tty: true
        ports:
            - 8080:8080
        depends_on:
            - db
            - broker
            - lfg-api

    flower:
        image: mher/flower
        container_name: flower
        environment:
            - FLOWER_PORT=5555
            - CELERY_BROKER_URL=pyamqp://guest:guest@broker//
        ports:
            - "5555:5555"
        depends_on:
            - broker

volumes:
    pgdata: